"""Fix broken foreign keys

Revision ID: 606000c6d277
Revises: d2bf76038e96
Create Date: 2023-09-27 23:18:46.071127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606000c6d277'
down_revision: Union[str, None] = 'd2bf76038e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fair_proxy_stall_id_fkey', 'fair_proxy', type_='foreignkey')
    op.create_foreign_key(None, 'fair_proxy', 'stall', ['stall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fair_proxy', type_='foreignkey')
    op.create_foreign_key('fair_proxy_stall_id_fkey', 'fair_proxy', 'fair', ['stall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
