"""Add Fair and Hall table

Revision ID: 1ff3bee55bed
Revises: cd11e4501567
Create Date: 2023-09-26 17:39:40.524808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff3bee55bed'
down_revision: Union[str, None] = 'cd11e4501567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
                    sa.Column('parking', sa.Boolean(), nullable=False),
                    sa.Column('internet', sa.Boolean(), nullable=False),
                    sa.Column('dissability', sa.Boolean(), nullable=False),
                    sa.Column('pets', sa.Boolean(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('city', sa.String(), nullable=False),
                    sa.Column('street', sa.String(), nullable=False),
                    sa.Column('zipcode', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('size', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fair',
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.Column('published', sa.Boolean(), nullable=False),
                    sa.Column('organizer_id', sa.Integer(), nullable=False),
                    sa.Column('hall_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['hall_id'], ['hall.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['organizer_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fair')
    op.drop_table('hall')
    # ### end Alembic commands ###
