"""Add Notification and Stall tables

Revision ID: 2cb6b12db4a3
Revises: 4032ec249f37
Create Date: 2023-09-26 21:59:20.818886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb6b12db4a3'
down_revision: Union[str, None] = '4032ec249f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('electricity', sa.Boolean(), nullable=False),
    sa.Column('network', sa.Boolean(), nullable=False),
    sa.Column('support', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stall')
    # ### end Alembic commands ###
