"""Add Industry and Image tables

Revision ID: 4032ec249f37
Revises: c5eabcec65dc
Create Date: 2023-09-26 21:30:14.090682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4032ec249f37'
down_revision: Union[str, None] = 'c5eabcec65dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ind_table = op.create_table('industry',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('name', sa.String(), nullable=False),
                                sa.Column('icon', sa.String(), nullable=False),
                                sa.Column('color', sa.String(),
                                          nullable=False),
                                sa.PrimaryKeyConstraint('id')
                                )
    op.create_table('image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('hall_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['hall_id'], ['hall.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('company_industry',
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('industry_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
                    sa.ForeignKeyConstraint(
                        ['industry_id'], ['industry.id'], ),
                    sa.PrimaryKeyConstraint('company_id', 'industry_id')
                    )
    op.create_table('fair_industry',
                    sa.Column('fair_id', sa.Integer(), nullable=False),
                    sa.Column('industry_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['fair_id'], ['fair.id'], ),
                    sa.ForeignKeyConstraint(
                        ['industry_id'], ['industry.id'], ),
                    sa.PrimaryKeyConstraint('fair_id', 'industry_id')
                    )

    op.bulk_insert(ind_table,
                   [
                       {"name": "Technologies & Software",
                           "icon": "devices", "color": "blue"},
                       {"name": "Healthcare", "icon": "medication", "color": "red"},
                       {"name": "Financial Services",
                           "icon": "monetization_on", "color": "amber-lighten-1"},
                       {"name": "Retail & E-commerce",
                           "icon": "storefront", "color": "black"},
                       {"name": "Energy", "icon": "bolt", "color": "yellow"},
                       {"name": "Automotive", "icon": "garage",
                           "color": "grey-darken-1"},
                       {"name": "Aerospace", "icon": "flight",
                           "color": "blue-lighten-3"},
                       {"name": "Food & Beverage",
                           "icon": "restaurant", "color": "red"},
                       {"name": "Entertainment & Media",
                           "icon": "live_tv", "color": "purple"},
                       {"name": "Transportation & Logistics",
                           "icon": "local_shipping", "color": "grey-darken-1"},
                       {"name": "Education & E-learning",
                           "icon": "school", "color": "blue"},
                       {"name": "Agriculture & Agribusiness",
                           "icon": "agriculture", "color": "green"},
                       {"name": "Legal Services", "icon": "gavel",
                           "color": "brown-darken-1"},
                       {"name": "Sports & Recreation",
                           "icon": "fitness_center", "color": "red-lighten-1"},
                       {"name": "Biotechnology", "icon": "biotech", "color": "green"},
                       {"name": "Gaming & Entertainment",
                           "icon": "sports_esports", "color": "red"},
                       {"name": "Architecture",
                           "icon": "architecture", "color": "green"},
                       {"name": "Fashion", "icon": "diamond",
                           "color": "pink-lighten-2"},
                       {"name": "Environmental Services",
                           "icon": "water_drop", "color": "blue"},
                       {"name": "Real Estate", "icon": "apartment",
                           "color": "grey-darken-1"}
                   ])
    # ### end Alembic commands ###

    def downgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.execute(r"DELETE FROM industry WHERE id > 0")
        op.drop_table('fair_industry')
        op.drop_table('company_industry')
        op.drop_table('image')
        op.drop_table('industry')
        # ### end Alembic commands ###
