"""Add missing column

Revision ID: e5d7326e242a
Revises: d2bf76038e96
Create Date: 2023-10-13 21:40:28.217404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d7326e242a'
down_revision = 'd2bf76038e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###
